name: physics_engine_env
channels:
  - defaults
dependencies:
  - python=3.10 # Updated to Python 3.10 for tinygrad compatibility
  - numpy
  - pip:
    - tinygrad # tinygrad is often installed via pip